# Generated by Django 2.2.7 on 2020-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20200228_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='couponID',
            field=models.CharField(default='AAAAAA', max_length=6),
        ),
    ]
