# Generated by Django 2.2.7 on 2020-02-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_user_couponid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='couponID',
            field=models.CharField(max_length=6),
        ),
    ]
